### ISSUE TITLE
Doesn't support PHP 7.4 version? Error message displayed

### ISSUE THREAD

**Issue by mrstevekim** [kamilwylegala/cakephp2-php8#40]
```
PHP Fatal error:  Declaration of CakeRequest::offsetExists(mixed $name): bool must be compatible with ArrayAccess::offsetExists($offset) in /Users/blahblah/development/cakephp2-php8/lib/Cake/Network/CakeRequest.php on line 1149

Fatal error: Declaration of CakeRequest::offsetExists(mixed $name): bool must be compatible with ArrayAccess::offsetExists($offset) in /Users/blahblah/development/cakephp2-php8/lib/Cake/Network/CakeRequest.php on line 1149
PHP Fatal error:  Uncaught Error: Class 'CakeRequest' not found in /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/L10n.php:433
Stack trace:
#0 /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/L10n.php(371): L10n->_autoLanguage()
#1 /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/I18n.php(221): L10n->get(NULL)
#2 /Users/blahblah/development/cakephp2-php8/lib/Cake/basics.php(636): I18n::translate('%s in [%s, line...', NULL, 'cake_console')
#3 /Users/blahblah/development/cakephp2-php8/lib/Cake/Console/ConsoleErrorHandler.php(83): __d('cake_console', '%s in [%s, line...', 'Declaration of ...', '/Users/blahblah/...', 1149)
#4 /Users/blahblah/development/cakephp2-php8/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(64, 'Declaration of ...', '/Users/blahblah/...', 1149, Array)
#5 /Users/blahblah/development/cakephp2-php8/lib/Cake/Core/App.php(943): App::_checkFatalError()
#6 [internal function]: App::shutdown()
#7 {main}
  thrown in /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/L10n.php on line 433

Fatal error: Uncaught Error: Class 'CakeRequest' not found in /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/L10n.php:433
Stack trace:
#0 /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/L10n.php(371): L10n->_autoLanguage()
#1 /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/I18n.php(221): L10n->get(NULL)
#2 /Users/blahblah/development/cakephp2-php8/lib/Cake/basics.php(636): I18n::translate('%s in [%s, line...', NULL, 'cake_console')
#3 /Users/blahblah/development/cakephp2-php8/lib/Cake/Console/ConsoleErrorHandler.php(83): __d('cake_console', '%s in [%s, line...', 'Declaration of ...', '/Users/blahblah/...', 1149)
#4 /Users/blahblah/development/cakephp2-php8/lib/Cake/Core/App.php(970): ConsoleErrorHandler->handleError(64, 'Declaration of ...', '/Users/blahblah/...', 1149, Array)
#5 /Users/blahblah/development/cakephp2-php8/lib/Cake/Core/App.php(943): App::_checkFatalError()
#6 [internal function]: App::shutdown()
#7 {main}
  thrown in /Users/blahblah/development/cakephp2-php8/lib/Cake/I18n/L10n.php on line 433
```

**Comment by kamilwylegala** [comment]
Hey, there is no compatibility promise for PHP 7.4. If you want to keep using 7.4, please stay with original CakePHP 2.*.

**Comment by mrstevekim** [comment]
The latest CakePHP 2.x is now gone from the official repositories. where can i download it?

**Comment by hiroya-ff** [comment]
> The latest CakePHP 2.x is now gone from the official repositories. where can i download it?

Here you are.

https://github.com/cakephp/cakephp/releases/tag/2.10.24
